spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/aula_teste_clientes
    password: 1234
    username: postgres
    driverClassName: org.postgresql.Driver
